AndApp/Models/CarDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AndApp.Models
{
    public class CarDetails
    {
        public string policytype { get; set; }
        public int stateid { get; set; }
        public string cityname { get; set; }

        public string rtocode { get; set; }
        public int makeid { get; set; }
        public int modelid { get; set; }
        public int variantid { get; set; }
        public string fueltype { get; set; }
        public int manufacturingyear { get; set; }
        public string regno { get; set; }

    
public string policystartdate { get; set; }
        public string policyenddate { get; set; }
        public string existingpolicyexpired { get; set; }
        public string claimtaken { get; set; }
    }
}

AndApp/Areas/Motor/Controllers/PrivateCarController.cs
using AndApp.Models;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AndWebApi.FGI;
using Newtonsoft.Json;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using System.Web.Script.Serialization;
using System.Net;
using System.Text;
using System.Net.Http.Headers;
using AndApp.AuthData;
using System.Security.Cryptography;
using SelectPdf;
using System.IO;
using System.Configuration;
using RestSharp;
using System.Net.Security;
using System.Data.Entity.Core.Objects;
using AndApp.Utilities;
using static AndApp.Models.SearchCriteria;
using System.Data;

using System.Net.Mime;
using static AndApp.Models.CommonModels;
using static AndApp.Utilities.Common;

namespace AndApp.Areas.Motor.Controllers
{


    public class PrivateCarController : Controller
    {
        DAL_CommonCls objcls = new DAL_CommonCls();

        DAL.ANDAPPEntities ap = new DAL.ANDAPPEntities();

        CRMAPIController datacrm = new CRMAPIController();



        public ActionResult Downloadd(string fileName)

        {

            //var g = Path.GetFileName(fil);
            //g.SaveAs("https://pipuat.tataaiginsurance.in/tagichubws/motor_policy.jsp?polno=064001/0177533393/000000/00&src=app&key=C0MJOrWjkbNYtMKbOKiV2LiDs", "gg");
            return View();
        }

        public ActionResult s()
        {

            string icici_token = GeticiciTokenNo("Generic");


            var client = new RestClient("https://ilesbsanity.insurancearticlez.com/ILServices/Misc/v1/Generic/PolicyCertificate?policyNo=3001/51992405/00/000");
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            request.AddHeader("Authorization", "Bearer " + icici_token);
            IRestResponse response = client.Execute(request);
            Console.WriteLine(response.Content);

            var result = response.Content;
            byte[] results = response.RawBytes;
            Stream stream = new MemoryStream(results);
            stream.Flush();
            stream.Position = 0;

            return File(stream, "application/pdf", "Labels.pdf");
        }
        public string GeticiciTokenNo(string scope)
        {
            string icici_token = "";

            var token_client = new RestClient(ConfigurationManager.AppSettings["ICICIToken"].ToString());

            ServicePointManager.ServerCertificateValidationCallback = new RemoteCertificateValidationCallback(delegate { return true; });
            ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;

            var token_request = new RestRequest("/cerberus/connect/token", Method.POST);

            token_request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            token_request.AddHeader("Accept", "application/json");
            token_request.AddParameter("grant_type", "password");
            token_request.AddParameter("username", "NodibSoftwares");
            token_request.AddParameter("password", "N@d!b$of6war35");
            if (scope == "Payment")
            {
                token_request.AddParameter("scope", "esbpayment");

            }
            else if (scope == "Generic")
            {
                token_request.AddParameter("scope", "esbgeneric");
            }
            else
            {
                token_request.AddParameter("scope", "esbmotor");
            }

            token_request.AddParameter("client_id", "ro.NodibSoftwares");
            token_request.AddParameter("client_secret", "ro.N@d!b$of6war35");

            var token_response = token_client.Post(token_request);

            if (token_response.StatusCode == HttpStatusCode.OK)
            {
                var token_data = (JObject)JsonConvert.DeserializeObject(token_response.Content.ToString());
                icici_token = token_data["access_token"].Value<string>();
            }
            return icici_token;
        }
        // GET: PrivateCar
        [HttpGet]
        public ActionResult DIGITPaymentFail(string errorMsg)
        {

            return RedirectToAction("thankyouurl", new { Response = errorMsg });
        }
        [HttpGet]
        public ActionResult DIGITPaymentSuccess(string applicationid, string policyno, string transactionNumber)
        {
            LogU.WriteLog("DIGITPaymentSuccess start " + policyno + "");
            ANDAPPEntities andent = new ANDAPPEntities();
            long userid = 0;
            TempData["applicationid"] = applicationid;
            TempData["policyno"] = policyno;
            var GetEnqNo = ap.GET_Payment_Parameter(policyno, 6).ToList();//18-06-2021 Todays Changes
            if (GetEnqNo.Count > 0)
            {
                string enqno = GetEnqNo[0].enq_id;
                var pospid = ap.VW_POLICYDETAILSMASTER.Where(x => x.enquiryid == enqno && x.companyid == 6).FirstOrDefault();
                userid = (long)pospid.pospid;
                ap.SP_POLICYDETAILSMASTER("U", enqno, 6, pospid.pospid,
                                   null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                   null, null, null, null, null, null, null, null, null, null, null, null, policyno, null, null,
                                   null, null, 1, null, null, null, null, null, null, null, null, null, null, true);

                if (!string.IsNullOrEmpty(policyno))
                {
                    datacrm.FetchData(6, enqno, transactionNumber);
                }
              
                
                //ap.SP_POLICYDETAILSMASTER("U", enqno, 6, Common.MySession.UserDetail.userid, null, null, null, null, null,
                //                            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                //                            null, null, null, null, null, null, null, null, null, null, true);
                ap.SP_Payment_Parameter(enqno, 6, "TransactionNumber", transactionNumber);
            }

            return RedirectToAction("thankyouurl", new { company = "DIGIT", response = "Pass", pospid = userid });
        }

        public ActionResult tatathankyouurl(string enqno)
        {
            string response = Request.QueryString.ToString();

            long userid = 0;
            if (response != null)
            {
                var responsedata = response.Split('=');
                if (responsedata != null)
                {

                    string enqid = responsedata[0].Substring(0, 13);
                    response = responsedata[1];
                    response = string.Concat(response.Reverse().Skip(6).Reverse());
                    response = response + "==";
                    byte[] data = Convert.FromBase64String(response);
                    string decodedString = Encoding.UTF8.GetString(data);

                    var proposal_resdata = (JObject)JsonConvert.DeserializeObject(decodedString.ToString());
                    var Data = proposal_resdata["data"];
                    var status = proposal_resdata["status"].ToString();
                    if (status == "1")

                    {
                        string policyno = Data["policyno"].ToString();
                        string mypno = "";
                        string rnd_str = Data["rnd_str"].ToString();
                        using (WebClient ccc = new WebClient())
                        {
                            mypno = policyno.Replace("/", "");
                            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                            ccc.DownloadFile("https://pipuat.tataaiginsurance.in/tagichubws/motor_policy.jsp?polno=064001/0177533393/000000/00&src=app&key=C0MJOrWjkbNYtMKbOKiV2LiDs", ConfigurationManager.AppSettings["savepdf"].ToString() + mypno + ".pdf");
                        }
                        TempData["tatapdf"] = "https://pipuat.tataaiginsurance.in/tagichubws/motor_policy.jsp?polno=" + policyno + "&src=app&key=" + rnd_str + "";
                        //ViewBag.pdfurl = ";
                        //ap.SP_POLICYDETAILSMASTER("U", enqid, 22, MySession.UserDetail.userid, null, null, null, null, null,
                        //                     null, null, null, null, null, null, null, null, null, null, null, null, mypno, null,
                        //                     null, null, null, null, null, null, null, null, null, null, true);
                        var pospid = ap.VW_POLICYDETAILSMASTER.Where(x => x.enquiryid == enqid && x.companyid == 22).FirstOrDefault();
                        userid = (long)pospid.pospid;
                        ap.SP_POLICYDETAILSMASTER("U", enqid, 22, pospid.pospid,
                                   null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                                   null, null, null, null, null, null, null, null, null, null, null, null, mypno, null, null,
                                   null, null, null, null, null, null, null, null, null, null, null, null, null, true);


                        if (!string.IsNullOrEmpty(mypno))
                        {
                            datacrm.FetchData(22, enqid,"");
                        }
                       
                        return RedirectToAction("thankyouurl", new { company = "tata", response = "Payment Successful" , pospid = userid });
                    }
                    else
                    {
                        return RedirectToAction("thankyouurl", new { company = "tata", response = "Payment Fail" });

                    }
                }
            }
            return RedirectToAction("thankyouurl", new { company = "tata", response = "Payment Fail" });
        }
        public ActionResult icicithankyouurl(string response)
        {
            LogU.WriteLog("ICICI OK");
            try
            {
                long userid = 0;

AndApp/Controllers/PrivateCarController.cs
using AndApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using DAL;

namespace AndApp.Controllers
{
    public class PrivateCarController : Controller
    {
        DAL_CommonCls objcls = new DAL_CommonCls();

        // GET: PrivateCar

        public ActionResult  CarDetails()
        {
            BindDropDown();
            return View();
        }
        public void BindDropDown()
        {
           ViewBag.makelist = GetMakeSelect();
            var myDate = DateTime.Now;

            List<SelectListItem> YearList = new List<SelectListItem>();
            for (int i = 0; i < 15; i++)
            {
                SelectListItem objselect = new SelectListItem();
                objselect.Text = myDate.ToString("yyyy");
                objselect.Value = myDate.Year.ToString();
                YearList.Add(objselect);
                myDate = myDate.AddYears(-1);
            }
            ViewBag.YearList = YearList.ToArray();
        }
        public JsonResult GetRto(int stateid)
        {
         var obj = objcls.GetAllRto(stateid,"");
          return Json(obj, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Getstate()
        {
            var obj = objcls.GetAllState().ToArray();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetMake()
        {
            var obj = objcls.GetMakeWithLogo().ToArray();
            return Json(obj, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GetModel(int makeid)
        {
            var obj = objcls.GetAllModel(makeid);
            var modelselect= (from db in obj select new
            {
                id = db.modelid,
                text = db.modelname

            }).ToList();
            return Json(new { model = obj.ToArray(), selectmodel = modelselect }, JsonRequestBehavior.AllowGet);
        }
     
        public JsonResult GetVariant(int modelid,string fueltype)
        {
            var obj = objcls.GetAllVariant(modelid,fueltype);
            var variantselect = (from db in obj
                               select new
                               {
                                   id = db.variantid,
                                   text = db.variantname

                               }).ToList();
            return Json(new { variant = obj.ToArray(), selectvariant = variantselect }, JsonRequestBehavior.AllowGet);
        }
        public List<SelectListItem> GetMakeSelect()
        {
            List<SelectListItem> selectlist = new List<SelectListItem>();
            try
            {
               var data = objcls.GetAllMake();
                for (int i = 0; i < data.Count; i++)
                {
                    SelectListItem objselect = new SelectListItem();
                    objselect.Value = data[i].makeid.ToString();
                    objselect.Text = data[i].makename.ToString();
                    selectlist.Add(objselect);
                }
            }
            catch (Exception Ex)
            {
                Console.Write(Ex.Message.ToString());
              
            }
            return selectlist;
        }
        public JsonResult GetManufacturingYear()
        {
            var myDate = DateTime.Now;
            List<SelectListItem> YearList = new List<SelectListItem>();
            for (int i = 0; i < 15; i++)
            {
                SelectListItem objselect = new SelectListItem();
                objselect.Text = myDate.ToString("yyyy");
                objselect.Value = myDate.Year.ToString();
                YearList.Add(objselect);
                myDate = myDate.AddYears(-1);
            }
            return Json(YearList.ToArray(), JsonRequestBehavior.AllowGet);
        }

    }
}

AndApp/Areas/Motor/Views/PrivateCar/GetStateCompanywise.cshtml
@{
    ViewBag.Title = "GetStateCompanywise";
}

<h2>GetStateCompanywise</h2>

AndApp/Areas/Motor/Views/PrivateCar/HDFCThankyouUrl.cshtml
@{
    ViewBag.Title = "HDFCThankyouUrl";
}
<div ng-app="myApp">
    <div id="" ng-controller="myHDFCThankyouUrl">
        <section class="padding-sm succ-pay gray-bg m-top2">
            <div class="container">
                <div class="row row justify-content-center">
                    <div class="col-md-4 col-lg-3">
                        <div class="p-box succ-left">
                            <div class="p-4 align-self-center">
                                <a href="@Url.Action("CarDetails","PrivateCar")" class="btn btn-pink">Dashboard</a>
                                <a href="@Url.Action("MyPolicy","PrivateCar")" class="btn btn-pink">My Policy</a>
                                <a href="@Url.Action("QuotationList", "QuotationList")" class="btn btn-pink">My Quote</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-lg-7">
                        <div class="p-box p-4">
                            <div class="row-box succ-head">
                                <div class="left-icon">
                                    <i class="fa fa-check-circle" aria-hidden="true"></i> <h5>Payment Successful</h5>
                                </div>
                                @*<p class="ml-auto">7 June 2021 20:15</p>*@
                            </div>
                            
                                <div class="succ-cont">
                                    <p style="color:red">@ViewBag.ErrMsg</p>
                                    <p>Dear @ViewBag.pospname ,</p>
                                    <p>Thank you for doing Business with ANDAPP.</p>
                                    @*<p>Payment for the Quotation no Q123-185 has been successfully done.</p>*@
                                    @*<p>Click Here to download the Policy copy <a href="#" ng-click="DownloadPolicy();" class="pink-color">Download Policy PDF</a></p>*@
                                    @*<p>Commission amount of 25000 is credited to your account bearing the account number xxxxxx890.</p>*@
                                </div>
                                <div class="row-box succ-foot">
                                    <a href="http://andapp.in/" class="gray-color">www.andapp.in/help</a>
                                    @*<p class="mb-0 ml-auto">Invoice ID:101010</p>*@
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

<script src="~/assets/js/angular.min.js"></script>
<script src="~/assets/js/ngStorage.min.js"></script>
<script src="~/assets/js/angular-filter.js"></script>

AndApp/Areas/Motor/Views/PrivateCar/Payment.cshtml
@{
    ViewBag.Title = "Payment";
    Layout = null;
}

<form action="https://uatpg.hdfcergo.com/PaymentGateway/Payments.aspx" method="post" target="_blank">
    <label for="Trnsno">TransactionID:</label>
    <input type="text" id="Trnsno" name="Trnsno"><br><br>

    <label for="FeatureID">FeatureID:</label>
    <input type="text" id="FeatureID" name="FeatureID"><br><br>

    <label for="CheckSum">CheckSum:</label>
    <input type="text" id="Checksum" name="CheckSum"><br><br>

    <input type="submit" value="Submit">
</form>

AndApp/Areas/Motor/Views/PrivateCar/PaymentFail.cshtml
@{
    ViewBag.Title = "PaymentFail";
}

<section class="padding-sm succ-pay gray-bg m-top2">
    <div class="container">
        <div class="row row justify-content-center">
            <div class="col-md-4 col-lg-3">
                <div class="p-box succ-left">
                    <div class="p-4 align-self-center">
                        <a href="@Url.Action("CarDetails","PrivateCar")" class="btn btn-pink">Dashboard</a>
                        <a href="@Url.Action("MyPolicy","PrivateCar")" class="btn btn-pink">My Policy</a>
                        <a href="@Url.Action("QuotationList", "QuotationList")" class="btn btn-pink">My Quote</a>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-7">
                <div class="p-box p-4">
                    <div class="row-box succ-head">
                        <div class="left-icon">
                            <i class="fa fa-check-circle" aria-hidden="true"></i> <h5>Payment Fail</h5>
                        </div>
                        <p class="ml-auto">7 June 2021 20:15</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

AndApp/Areas/Motor/Views/PrivateCar/PaymentSuccess.cshtml
@{
    ViewBag.Title = "PaymentSuccess";
}

<div ng-app="myApp">
    <div id="" ng-controller="myPaymentSuccess">
        <section class="padding-sm succ-pay gray-bg m-top2">
            <div class="container">
                <div class="row row justify-content-center">
                    <div class="col-md-4 col-lg-3">
                        <div class="p-box succ-left">
                            <div class="p-4 align-self-center">
                                <a href="@Url.Action("CarDetails","PrivateCar")" class="btn btn-pink">Dashboard</a>
                                <a href="@Url.Action("MyPolicy","PrivateCar")" class="btn btn-pink">My Policy</a>
                                <a href="@Url.Action("QuotationList", "QuotationList")" class="btn btn-pink">My Quote</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8 col-lg-7">
                        <div class="p-box p-4">
                            <div class="row-box succ-head">
                                <div class="left-icon">
                                    <i class="fa fa-check-circle" aria-hidden="true"></i> <h5>Payment Successful</h5>
                                </div>
                                <p class="ml-auto">7 June 2021 20:15</p>
                            </div>
                            @if (ViewBag.ErrMsg == "")
                            {
                                <div class="succ-cont">
                                    <p>Dear Hemant Darji,</p>
                                    <p>Thank you for doing Business with ANDAPP.</p>
                                    @*<p>Payment for the Quotation no Q123-185 has been successfully done.</p>*@
                                    @*<p>Click Here to download the Policy copy <a href="#" ng-click="DownloadPolicy();" class="pink-color">Download Policy PDF</a></p>*@
                                    @*<p>Commission amount of 25000 is credited to your account bearing the account number xxxxxx890.</p>*@
                                </div>
                                <div class="row-box succ-foot">
                                    <a href="http://andapp.in/" class="gray-color">www.andapp.in/help</a>
                                    @*<p class="mb-0 ml-auto">Invoice ID:101010</p>*@
                                </div>
                            }
                            else
                            {
                                <div class="succ-cont">
                                    <p style="color:red">@ViewBag.ErrMsg</p>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
<script src="~/assets/js/angular.min.js"></script>
<script src="~/assets/js/ngStorage.min.js"></script>
<script src="~/assets/js/angular-filter.js"></script>

@*<script type="text/javascript">

    var app = angular.module("myApp", ["ngStorage", "angular.filter"]);

    app.controller("myPaymentSuccess", function ($scope, $http, $window, $compile, $sessionStorage, $filter) {
         
        $scope.DownloadPolicy = function () {
            debugger
         
            var policyno = '@ViewBag.PolicyNo';
            alert(policyno);

            $window.location.href = '/Motor/PrivateCar/PaymentSuccess?policyno=' + policyno;
        }
    });
</script>*@

AndApp/Areas/Motor/Views/PrivateCar/s.cshtml
@{
    ViewBag.Title = "s";
}

<h2>s</h2>

AndApp/Areas/Motor/Views/PrivateCar/sort.cshtml
@{
    ViewBag.Title = "sort";
    Layout = null;
}
<br /><br /><br /><br /><br /><br />
<a  class="form-control" href="https://pipuat.tataaiginsurance.in/tagichubws/motor_policy.jsp?polno=064001/0177532587/000000/00&src=app&key=wFE6cHPjXABbJpuxDLV1ClpOr" download>download pdf</a>
 @*<html>

<body onload='document.forms[0].submit()'>
    <form action='https://pay.tataaig.com/CPIUAT1/_tataaig_payment' method='post'>
        <input type='hidden' value='HrpdZPthOJPUNeDVVfevrX2bLLi8v5NXjjXNaRGf3uCsrNqoR3ROYa5Jp5Zm36Ocud9fHYOYzjbQ4W/6sujKObIfFLsZHtvJmPXcECaAGixjowJRXuUbisJ/QoRbDKeNOrd5ZV4RN/Fn47Q7TvKZhCi5VBnnk2eWEPGJqwxzp/Cnr7sZ4kThHR2QXWCSWBhfOa2g+Fr0ABs+nwzSK2yPGi5m7aCPkruNWga7Ex5ZzO9uC/bYtrSlDomd3rwlxh1ztClz/PMbv/JfzccUuHML2L++j86LoS1tCpSDIWoojYQSAu7jybHFsFhyQIF8HybocYVtn1kb+DRNpCtSyC4onebGRpjrOV1T+Sv1ny7VA6ojQBiUouQoDifoG4EKCC/z7LOsQZSfmkL2a8Kciw6EfavLivsg42BtTVU0nxJcl7yWoBrc4o+/GjwZrlVfyQKAiOIC94ejCzqY9dwQJoAaLPLEj8EY11buAufp7anr60ztm/IWZvfG+dVCl4/IiYK9XWx/veq5YVLPxWIoUnk6jKys2qhHdE5hv1nKrnwTJocP1570h+Tl+EiCD2TicE8x1ZoLaWln8AR1QlwP+Tj5EaFcwo+IYvO1IzkWfjIf5kHIi65/b9fuKZ2oRpeHVwr35QG1Q2KHrsd43TXhglZO5/GXSqyZdHzvPtIA2Cb78aUJ8UL74B3y/BrlA0JJKa3oDNGmHrE3yTVfUxjA99NY7XYdGDauoOGOvsBkBX8TViRsbPCp3I10NvXlYjMvXbbzxV0vvMdvXCsVE7/cSV6tYg==' name='pgiRequest' />
    </form>
</body>

</html>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head id="Head1">
    <title>PG Integration</title>
    <style>
        img.centerImg {
            position: absolute;
            top: 50%;
            left: 50%;
        }

        div.centerText {
            position: absolute;
            text-align: center;
            left: 40%;
            top: 55%;
            width: 20%;
        }
    </style>
</head>

<body>
    <center>
        <img id="progress" src="images\status.gif" class="centerImg" style="display:show;">
        <div class='centerText'>Loading..Please Wait...</div>
    </center>
    <div id="div1">
        <table width='100%' border=0 cellspacing="0" style="border-width:inherit;background-color:#005BAB;">
            <tr>
                <td width="100%">&nbsp; <img src="images\pg_header.jpg" align='right'></img></td>
            </tr>
        </table>
    </div>
</body>

</html>*@

AndApp/Areas/Motor/Views/PrivateCar/thankyouurl.cshtml
@{
    ViewBag.Title = "thankyouurl";

    
}




<section class="padding-sm succ-pay gray-bg m-top2">
    <div class="container">
        <div class="row row justify-content-center">
            <div class="col-md-4 col-lg-3">
                <div class="p-box succ-left">
                    <div class="p-4 align-self-center">
                        @*<a href="@Url.Action("cardet class="btn btn-pink">New Quote</a>
                            <a href="#" class="btn btn-pink">My Policy</a>
                            <a href="@Url.Action("Quotat class="btn btn-pink">My Quote</a>*@
                        <a href="@Url.Action("CarDetails","PrivateCar")" class="btn btn-pink">Dashboard</a>
                        <a href="@Url.Action("MyPolicy","PrivateCar")" class="btn btn-pink">My Policy</a>
                        <a href="@Url.Action("QuotationList", "QuotationList")" class="btn btn-pink">My Quote</a>
                    </div>
                </div>
            </div>
            <div class="col-md-8 col-lg-7">
                <div class="p-box p-4">
                    <div class="row-box succ-head">
                        <div class="left-icon">
                            <i class="fa fa-check-circle" aria-hidden="true"></i> <h5>@ViewBag.payment</h5>
                        </div>

                    </div>
                    @if (ViewBag.payment == "Payment Successful")
                    {



                        <div class="succ-cont">
                            <p>Dear @ViewBag.pospname</p>
                            <p>Thank you for doing Business with ANDAPP.</p>
                           
                            @if (ViewBag.pdfurl == "serviceerror")
                            {
                                <p>Click Here to download the Policy copy <a href="#" onclick="Pdferror('serviceerror');" class="pink-color">Download Policy PDF</a></p>
                            }
                            else if (ViewBag.pdfurl == "error" || ViewBag.pdfurl == "")
                            {
                                <p>Click Here to download the Policy copy <a  href="#" onclick="Pdferror('error');" class="pink-color">Download Policy PDF</a></p>
                            }
                            else
                            {
                                <p>Click Here to download the Policy copy <a href="@ViewBag.pdfurl" class="pink-color">Download Policy PDF</a></p>
                            }

                            @*<p>Commission amount of 25000 is credited to your account bearing the account number xxxxxx890.</p>*@
                        </div>
                        <div class="row-box succ-foot">
                            <a href="http://andapp.in/" class="gray-color">www.andapp.in/help</a>
                          
                        </div>}
                </div>
            </div>


        </div>

    </div>
</section>

<script type="text/javascript">

    if ('@ViewBag.company' == 'ICICI') {

        window.location.href = '@Url.Action("ICICPDF", "PrivateCar")';
    }
    function Pdferror(status) {
        if (status == "serviceerror")
            alert("Digit Internal Service is not working");
        else
            alert("This Policy is under Inspection");
    }
</script>